name: Continuous Integration Workflow
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Debug Info'
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of directory:"
          ls -la

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run tests'
        run: npm run test
